version: '3'

services:
  # HTTP/HTTPS test sunucusu
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./tests/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./tests/nginx/ssl:/etc/nginx/ssl:ro

  # SSH test sunucusu
  ssh:
    image: linuxserver/openssh-server:latest
    ports:
      - "22:22"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - USER_NAME=test
      - USER_PASSWORD=test123

  # FTP test sunucusu
  ftp:
    image: fauria/vsftpd:latest
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=test
      - FTP_PASS=test123
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110

  # SMTP test sunucusu
  smtp:
    image: mailhog/mailhog:latest
    ports:
      - "25:1025"
      - "8025:8025"

  # RDP test sunucusu (Windows container)
  rdp:
    image: cmulk/windows-rdp:latest
    ports:
      - "3389:3389"
    environment:
      - RDP_USER=test
      - RDP_PASS=test123 